# Generated by Django 4.1 on 2022-08-21 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='error', upload_to='pics'),
            preserve_default=False,
        ),
    ]
